function sebas() {
    document.getElementById("con").innerHTML = ""
    +"<form class='form-register'>"
    +"<br><br><br><br><br>" 
    +"<section>"
    +"<input class='controls1' type='text' name='nombres' id='nombres' placeholder='Nombre'><br>"
    +"<input class='controls2' type='text' name='apellidos' id='apellidos' placeholder='Apellido'><br>"
    +"<input class='controls3' type='email' name='correo' id='correo' placeholder='Correo'><br>"
    +"<select  class='opciones'>"
        +"<option>Tarjeta De Identidad</option>"
        +"<option>Numero de documento</option>"
    +"</select>"
    +"<input class='controls4' type='text'name='numero' de documento' id='numero de documento' placeholder='Numero de Documento'><br>"
    +"<input class='controls5' type='password' name='correo' id='correo' placeholder='Contraseña'><br>"
    +"<button><a class='boton href='#'>Agregar</a></button>"
    +"<button><a class='boton'href='menu.html'>Regresar</a></button>"
    
 
   +"</section>"
 +"</form>"
}

function sebas1() {
    document.getElementById("con").innerHTML = ""
     +"<center>"
    +"<div class='container'>"
        +"<table>"
            +"<thead>"     
                +"<tr>"
                +"<br><br><br><br><br>" 
                    +"<th>N°</th>"
                    +"<th>Nombre</th>"
                    +"<th>Apellidos</th>"
                    +"<th>numero de documento</th>"
                    +"<th>correo</th>"
                    +"<th>numero de telefono</th>"
                +"</tr>"
            +"</thead>"
            +"<tbody>"
                +"<tr>"
                    +"<td>01</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>02</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>03</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>04</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>05</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
            +"</tbody>"
        +"</table>"
    +"</div>" 
    +"<center/>";
}

function sebas2() {
    document.getElementById("con").innerHTML = ""
    +"<form>"
    +"<section class='form-register'>"
        +"<br><br><br><br><br>"
      +"<input class='controls1' type='text' name='nombres' id='nombres' placeholder='placa'>"
      +"<input class='controls2' type='text' name='apellidos' id='apellidos' placeholder='marca del carro'>"
      +"<input class='controls3' type='text' name='correo' id='correo' placeholder='dueño del carro'>"
      +"<input class='controls4' type='text' name='correo' id='correo' placeholder='color'>"
      +"<center>"
        +"<button><a class='boton' href='#'>Agregar</a></button>"
        +"<button><a class='boton' href='menu.html'>Regresar</a></button>"
      +"</center>"
    +"</section>"
    +"</form>" 
}

function sebas3() {
    document.getElementById("con").innerHTML = ""
    +"<center>"
    +"<div class='container'>"
        +"<table>"
            +"<thead>"     
                +"<tr>"
                +"<br><br><br><br><br>" 
                    +"<th>N°</th>"
                    +"<th>Placa</th>"
                    +"<th>Marca</th>"
                    +"<th>Modelo</th>"
                    +"<th>DUeño</th>"
                    +"<th>Color</th>"
                +"</tr>"
            +"</thead>"
            +"<tbody>"
                +"<tr>"
                    +"<td>01</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>02</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>03</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>04</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>05</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
            +"</tbody>"
        +"</table>"
    +"</div>" 
    +"<center/>";
}

function sebas4() {
    document.getElementById("con").innerHTML = ""
    +"<section class='form-register'>"
    +"<br><br><br><br><br>" 
    +"<input class='controls1' type='text' name='nombres' id='nombres' placeholder='placa'>"
    +"<input class='controls2' type='text' name='apellidos' id='apellidos' placeholder='identificacion'>"
    +"<h1>fecha</h1>"
    +"<input class='controls3' type='date' name'correo' id='correo' placeholder='fecha'>"
    +"<input class='controls4' type='text' name='correo' id='correo' placeholder='tipo'>"
    +"<select class='opciones'>"
        +"<option>cargar</option>"
        +"<option>listar</option>"
        +"<option>publicar</option>"
    +"</select>"
    +"<center>"
    +"<button><a class='boton' href='#'>Agregar</a></button>"
    +"<button><a class='boton' href='menu.html'>Regresar</a></button>"
  +"</center>"
  +"</section>"
}

function sebas5() {
    document.getElementById("con").innerHTML = ""
    +"<center>"
    +"<div class='container'>"
        +"<table>"
            +"<thead>"     
                +"<tr>"
                +"<br><br><br><br><br>" 
                    +"<th>N°</th>"
                    +"<th>Cambio de aceite</th>"
                    +"<th>Cincronización</th>"
                    +"<th>Alineación</th>"
                    +"<th>lavado</th>"
                +"</tr>"
            +"</thead>"
            +"<tbody>"
                +"<tr>"
                    +"<td>01</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>02</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>03</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>04</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>05</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
            +"</tbody>"
        +"</table>"
    +"</div>" 
    +"<center/>";
}

function sebas6() {
    document.getElementById("con").innerHTML = ""
    +"<center>"
    +"<div class='container'>"
        +"<table>"
            +"<thead>"     
                +"<tr>"
                +"<br><br><br><br><br>" 
                    +"<th>N°</th>"
                    +"<th>Carro</th>"
                    +"<th>Servicio</th>"
                    +"<th>Fecha</th>"
                    +"<th>Lavado</th>"
                +"</tr>"
            +"</thead>"
            +"<tbody>"
                +"<tr>"
                    +"<td>01</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>02</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>03</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>04</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
                +"<tr>"
                    +"<td>05</td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                    +"<td><input type='text'></td>"
                +"</tr>"
            +"</tbody>"
        +"</table>"

    +"</div>" 
    +"<center/>";
}


